### ISSUE TITLE
Core files are missing in final xCode project

### ISSUE THREAD

**Issue by brocococonut** [chrismear/renios#70] opened 2014-04-23 08:43 UTC
<code>
GenerateDSYMFile /Users/HtTYDDS/Library/Developer/Xcode/DerivedData/HtTYDDS-bcehxyekvxikpgbyddhsngtjuzqg/Build/Products/Debug-iphonesimulator/HtTYDDS.app.dSYM /Users/HtTYDDS/Library/Developer/Xcode/DerivedData/HtTYDDS-bcehxyekvxikpgbyddhsngtjuzqg/Build/Products/Debug-iphonesimulator/HtTYDDS.app/HtTYDDS
    cd /Users/HtTYDDS/Downloads/renios-0.3/app-HtTYDDS
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/HtTYDDS/Library/Developer/Xcode/DerivedData/HtTYDDS-bcehxyekvxikpgbyddhsngtjuzqg/Build/Products/Debug-iphonesimulator/HtTYDDS.app/HtTYDDS -o /Users/HtTYDDS/Library/Developer/Xcode/DerivedData/HtTYDDS-bcehxyekvxikpgbyddhsngtjuzqg/Build/Products/Debug-iphonesimulator/HtTYDDS.app.dSYM

</code>

<code>
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/ios.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/bufferproxy.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/key.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/base.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/imageext.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/constants.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/font.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/image.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/event.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/display.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/mouse.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/overlay.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/gfxdraw.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/SDL_gfx/SDL_gfxPrimitives.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/mask.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/bitmask.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/joystick.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/pixelarray.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/gen/renpy.display.accelerator.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/gen/_renpybidi.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/renpybidicore.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/gen/renpy.gl.gldraw.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/gen/renpy.text.textsupport.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/_arraysurfarray.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/draw.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/_camera.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/color.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/pygametime.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/surflock.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/_numericsurfarray.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/fastevent.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/fastevents.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/rwobject.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/rect.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/surface.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/alphablit.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/surface_fill.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/transform.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/rotozoom.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/scale2x.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.9-i386-2.7/src/scale_mmx.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/gen/_renpy.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/IMG_savepng.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/core.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/rwobject.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/subpixel.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/gen/renpy.text.ftfont.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/ftsupport.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/gen/renpy.text.texwrap.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/renpy_ttf.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/renpy_font.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/gen/renpy.gl.glrtt_copy.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/gen/renpy.gl.glenviron_shader_es.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/gen/renpy.gl.glrtt_fbo.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/gen/renpy.gl.gltexture.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/gen/renpy.display.render.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/gen/pysdlsound.sound.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/pss.o unable to open object file
warning: (i386) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/renpy-6.14.1-sdk/module/build/temp.macosx-10.9-i386-2.7/ffdecode.o unable to open object file
<code>

**Comment by chrismear** [comment] 2014-04-23 09:36
Duplicate of #66; see also comments on #69.

**Closed as completed by chrismear** 2014-04-23 09:36 UTC
